import React, { useState, useEffect } from "react";
import Head from 'next/head'
import { useRouter } from "next/router";

const Signup = function () {
    const [token, setToken] = useState(null);
    const [tokenIsNull, setTokenIsNull] = useState(true);
    const [username, setUsername] = useState(null);
    const router = useRouter();

    useEffect(() => {
        getUserToken();
    })
    
    const getUserToken = () => {
        let token = localStorage.getItem('codingthunder');
        if (token != null) {
            let parsedToken = JSON.parse(token);
            setToken(parsedToken.authtoken);
            setUsername(parsedToken.username);
            setTokenIsNull(false);
        } else {
            setTokenIsNull(true);
            if (tokenIsNull == true) {
                router.push('/accounts/login')
            }
        }
    }
    
    
    return (
        <>
            <Head>
                <title>My Account - CodingThunder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container my-3">
                <div className="jumbotron text-center">
                    <h2>My Account page is under maintainance and will be available soon!</h2>
                </div>
            </div>
        </>
    )
}

export default Signup