import React, { useState } from "react";
import Head from 'next/head'
import Link from "next/link"

const Blog = function (props) {
    const [blogs, setBlogs] = useState(props.allBlogs)
    return (
        <>
            <Head>
                <title>Blog - CodingThunder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container my-3">
                <h2>Browse coding articles: ({blogs.length})</h2>
                <hr />
                {blogs.map((blog) => {
                    return <div key={blog.slug} className="border shadow-sm p-3 rounded my-3">
                        <p className="text-muted mb-1">Published on <strong>{new Date(`${blog.timestamp}`).toDateString()}</strong></p>
                        <h3><Link className="text-dark" href={"/blogpost/" + blog.slug}>{blog.title}</Link></h3>
                        <p className="mb-2">{blog.tagline}</p>
                        <Link href={"/blogpost/" + blog.slug} className="btn btn-sm btn-outline-danger">Read More &raquo;</Link>
                    </div>
                })}
            </div>
        </>
    )
}


export async function getServerSideProps(context) {
    let res = await fetch(`http://localhost:3000/api/getblogs`);
    let data = await res.json();
    let allBlogs = data.blogs;

    return {
        props: {
            allBlogs
        }
    }
}

export default Blog