import React, { useState } from 'react'
import Head from 'next/head'
import Script from 'next/script';
import Alert from '../components/Alert';

const Signup = function () {
    const [contact, setContact] = useState({ name: "", email: "", phone: "", message: "" });
    const [alert, setAlert] = useState(null);

    const handleChange = (e) => {
        setContact(contact => ({ ...contact, [e.target.id]: `${e.target.value}` }))
    }

    const showAlert = (message, type) => {
        setAlert({
            msg: message,
            type: type
        })
        setTimeout(() => {
            setAlert(null);
        }, 1500);
    }

    const handleSubmit = async (e) => {
        if (!e.target.classList.contains('disabled') && !e.target.hasAttribute('disabled')) {
            e.target.classList.add('disabled');
            e.target.setAttribute('disabled', 'disabled');
            e.target.innerHTML = `Sending... <div class="spinner-border spinner-border-sm text-light" role="status"><span class="sr-only">Loading...</span></div>`;
            const response = await fetch('http://localhost:3000/api/contact', {
                method: "POST",
                headers: {
                    "Content-type": "application/json"
                },
                body: JSON.stringify(contact)
            })
            let data = await response.json();
            showAlert(`${data.message}`, `${data.status}`);
            if (data.status == "success") {
                document.getElementById("contactForm").reset();
                e.target.innerHTML = `Sent`;
            }
        }
    }

    return (
        <>
            <Head>
                <title>Contact Me - CodingThunder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Alert alert={alert} />
            <div className="container my-3">
                <h2>Contact Me</h2>
                <form id="contactForm">
                    <div className="form-group">
                        <label htmlFor="name">Name</label>
                        <input type="text" className="form-control" id="name" placeholder="Enter your full name" onChange={handleChange} />
                    </div>
                    <div className="form-group">
                        <label htmlFor="email">Email Address</label>
                        <input type="email" className="form-control" id="email" placeholder="Enter your email address" onChange={handleChange} />
                    </div>
                    <div className="form-group">
                        <label htmlFor="phone">Phone number (with country code)</label>
                        <input type="text" className="form-control" id="phone" placeholder="Enter your phone number" onChange={handleChange} />
                    </div>
                    <div className="form-group">
                        <label htmlFor="message">Message</label>
                        <textarea className="form-control" id="message" rows={3} placeholder="Describe your concern" onChange={handleChange} />
                    </div>
                    <div className="form-group">
                        <div class="g-recaptcha" data-sitekey="6Lf45MEiAAAAAKlPp8kFBD0JAE2XmYOLPk2LG9EE"></div>
                    </div>
                    <button type="button" className="btn btn-danger" onClick={handleSubmit}>Submit</button>
                </form>
            </div>

            <Script src="https://www.google.com/recaptcha/api.js" />
        </>
    )
}

export default Signup