import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - CodingThunder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container my-3">
        <div className="jumbotron text-center"></div>
      </div>
    </>
  )
}
