import React, { useState } from "react";
import Head from 'next/head'
import Link from "next/link"

const Search = function (props) {
    const [blogs, setBlogs] = useState(props.allBlogs)
    const { query } = props;
    console.log(query);

    return (
        <>
            <Head>
                <title>Search results for &quot;{query}&quot; - CodingThunder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container my-3">
                <h2>Search results for &quot;{query}&quot;: ({blogs.length})</h2>
                <hr />
                {blogs.length === 0 ? <><h5>Sorry! We have no search results available for &quot;{query}&quot;.</h5>
                    <p>Suggestions</p>
                    <ul>
                        <li>Make sure that all words are spelled correctly.</li>
                        <li>Try different keywords.</li>
                        <li>Try more general keywords.</li>
                        <li>Try fewer keywords.</li>
                    </ul></>
                    : blogs.map((blog) => {
                        return <div key={blog.slug} className="border shadow-sm p-3 rounded my-3">
                            <p className="text-muted mb-1">Published on <strong>{new Date(`${blog.timestamp}`).toDateString()}</strong></p>
                            <h3><Link className="text-dark" href={"/blogpost/" + blog.slug}>{blog.title}</Link></h3>
                            <p className="mb-2">{blog.tagline}</p>
                            <Link href={"/blogpost/" + blog.slug} className="btn btn-sm btn-outline-danger">Read More &raquo;</Link>
                        </div>
                    })}
            </div>
        </>
    )

}

export async function getServerSideProps(context) {
    const { query } = context.query;
    let res = await fetch(`http://localhost:3000/api/getblogs?search_query=${query}`);
    let data = await res.json();
    let allBlogs = data.blogs;

    return {
        props: {
            allBlogs: allBlogs, query: query
        }
    }
}

export default Search